In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
#importing the dataset
dataset = pd.read_csv('data_input/Social_Network_Ads.csv') #read_cv reads csv files into dataframe

In [11]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [12]:
x = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

In [13]:
print (y[0:5])
##print (x)

[0 0 0 0 0]


In [14]:
#splitting the dataset into the training adn test set
from sklearn.model_selection import train_test_split #cross_validation is now model_selection
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 0) #evaluate using 25 percent and correct is 80/20 split is good

In [15]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler #transforms data to have a mean value of 0 and standard deviation of 1
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [16]:
x_train[0:5,]

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358]])

In [19]:
#fitting logistic regression to the training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [20]:
#predicting the test set results
y_pred = classifier.predict(x_test)

In [21]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [22]:
#prints out confusion matrix
cm

array([[65,  3],
       [ 8, 24]])

In [ ]:
#visualizing the training set results
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
X1, X2 = np.meshgrid(np.arange(start = x_set[:,0].min() -1, stop = X_set[:,0].max() + 1, step = 0.01) np.arange(start = x_set[:,1].min() -1, stop = X_set[:,1].max() + 1, step = 0.01))
plt.contour(X1,X2, classifier.predict(np.array([X1.ravel])))